const UML_GENERATION = 'UML_GENERATION';

const UML_GENERATION_PENDING = 'UML_GENERATION_PENDING';
const UML_GENERATION_SUCCESS = 'UML_GENERATION_SUCCESS';
const UML_GENERATION_FAILURE = 'UML_GENERATION_FAILURE';


export {
     UML_GENERATION,
    UML_GENERATION_PENDING,
    UML_GENERATION_SUCCESS,
    UML_GENERATION_FAILURE
};